tomjo:olafa:Check for existence of app.jar

diff --git a/sti/bin/assemble b/sti/bin/assemble
--- a/sti/bin/assemble
+++ b/sti/bin/assemble
@@ -133,14 +133,16 @@ fi
 # As Microservices you should only have 1 fat jar
 # if compgen -G "/tmp/src/*" >/dev/null; then
 # TODO: Review how best move these
-if [ $(ls ${DEPLOY_DIR}/${APP_JAR_NAME}.jar | wc -l) -eq 1 ]; then
-  echo "[INFO] Copying ${DEPLOY_DIR}/${APP_JAR_NAME}.jar into ${DEPLOY_DIR}/app.jar"
-  cp ${DEPLOY_DIR}/${APP_JAR_NAME}.jar ${DEPLOY_DIR}/app.jar
-  [ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
-  echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
-else
-  echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}"
-  exit 1
+if [ ! -f ${DEPLOY_DIR}/app.jar ]; then
+  if [ $(ls ${DEPLOY_DIR}/${APP_JAR_NAME}.jar | wc -l) -eq 1 ]; then
+    echo "[INFO] Copying ${DEPLOY_DIR}/${APP_JAR_NAME}.jar into ${DEPLOY_DIR}/app.jar"
+    cp ${DEPLOY_DIR}/${APP_JAR_NAME}.jar ${DEPLOY_DIR}/app.jar
+    [ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
+    echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
+  else
+    echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}"
+    exit 1
+  fi
 fi
 
 exit 0
